### ISSUE TITLE
Getting Crash on App Launch

### ISSUE THREAD

**Issue by praveenathuru** [osipxd/encrypted-datastore#20]
Caused by: java.security.KeyStoreException: the master key android-keystore://_androidx_security_master_key_ exists but is unusable
	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewMasterKey(AndroidKeysetManager.java:276)
	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:237)
	at androidx.security.crypto.EncryptedFile$Builder.build(EncryptedFile.java:172)
	at com.huru.datastore.di.DataStoreModule$getDataStore$1.invoke(DataStoreModule.kt:61)
	at com.huru.datastore.di.DataStoreModule$getDataStore$1.invoke(DataStoreModule.kt:55)
	at io.github.osipxd.security.crypto.EncryptedPreferenceDataStoreFactoryKt.createEncrypted(EncryptedPreferenceDataStoreFactory.kt:61)
	at io.github.osipxd.security.crypto.EncryptedPreferenceDataStoreFactoryKt.createEncrypted$default(EncryptedPreferenceDataStoreFactory.kt:48)

**Comment by osipxd** [comment]
@praveenathuru, thank you for the report. Is it full stacktrace? Are there more causes?

**Comment by praveenathuru** [comment]
Not sure just got this one today as I launcher my app after 24 hours on Android 9.
I'm maintaining 2 different Data Stores variants in the application one for User and one for App level configuration.
This is how I'm maintaining data stores.

```
@Qualifier
@Retention(AnnotationRetention.BINARY)
annotation class AppDataStore

@Qualifier
@Retention(AnnotationRetention.BINARY)
annotation class UserDataStore

@Qualifier
@Retention(AnnotationRetention.RUNTIME)
annotation class UserDataStoreManager

@Qualifier
@Retention(AnnotationRetention.RUNTIME)
annotation class AppDataStoreManager

@Module
@InstallIn(SingletonComponent::class)
object DataStoreModule {
    @Provides
    @Singleton
    @UserDataStore
    fun provideUserDataPreference(@ApplicationContext context: Context): DataStore<Preferences> {
        return context.getDataStore(fileName = "huru_user_data.preferences_pb")
    }

    @Provides
    @Singleton
    @AppDataStore
    fun provideAppDataPreference(@ApplicationContext context: Context): DataStore<Preferences> {
        return context.getDataStore(fileName = "huru_app_data.preferences_pb")
    }

    private fun Context.getDataStore(fileName: String): DataStore<Preferences> {
        return PreferenceDataStoreFactory.createEncrypted {
            EncryptedFile.Builder(
                dataStoreFile(fileName = fileName),
                this,
                MasterKeys.getOrCreate(MasterKeys.AES256_GCM_SPEC),
                EncryptedFile.FileEncryptionScheme.AES256_GCM_HKDF_4KB
            ).build()
        }
    }

    @Provides
    @Singleton
    @UserDataStoreManager
    fun provideUserDataStoreManager(@UserDataStore dataStore: DataStore<Preferences>): DataStoreManager {
        return DataStoreManagerImpl(dataStore)
    }

    @Provides
    @Singleton
    @AppDataStoreManager
    fun provideAppDataStoreManager(@AppDataStore dataStore: DataStore<Preferences>): DataStoreManager {
        return DataStoreManagerImpl(dataStore)
    }
}
```

**Comment by osipxd** [comment]
There are many reasons why the library can't decrypt master key, but firstly I'd suggest updating [tink](https://github.com/tink-crypto/tink-java/) (the cryptographic library used under the hood) to the latest version:
```kotlin
dependencies {
    implementation("com.google.crypto.tink:tink-android:1.12.0")
}
```

If this does not help, look at this issue: https://github.com/tink-crypto/tink/issues/535 (especially [this](https://github.com/tink-crypto/tink/issues/535#issuecomment-912170221) comment and [this one](https://github.com/tink-crypto/tink/issues/535#issuecomment-1880996687))

**Comment by praveenathuru** [comment]
@osipxd any luck with this crash? we are facing crashes heavily in the production because of this.
Any workaround you suggest?
Did you updated the tink under the hood in this library?

**Comment by osipxd** [comment]
@praveenathuru, yes, I've updated Tink to the latest version [in v1.0.0](https://github.com/osipxd/encrypted-datastore/releases/tag/v1.0.0). Do you have fresh stack traces with an updated version?

**Comment by praveenathuru** [comment]
We are using `1.0.0-beta01` version since long, now planning to upgrade it to `v1.0.0`.
Hope [v1.1.1-beta03](https://github.com/osipxd/encrypted-datastore/releases/tag/v1.1.1-beta03) is not required at this point of time.

**Comment by osipxd** [comment]
> Hope [v1.1.1-beta03](https://github.com/osipxd/encrypted-datastore/releases/tag/v1.1.1-beta03) is not required at this point of time.

It is required only if you want to use datastore 1.1.0.

**Comment by osipxd** [comment]
@praveenathuru, have you had a chance to check if the problem persists on the new version?

**Comment by itamarb-ramm** [comment]
@osipxd I'm having the same crash but only on a galaxy a35 so far. Using version 1.1.1-beta03.

**Comment by osipxd** [comment]
> @osipxd I'm having the same crash but only on a galaxy a35 so far. Using version 1.1.1-beta03.
 
Could you tell me what version of Android are affected?

**Comment by itamarb-ramm** [comment]
Android 14. Seems to run fine on A53 also with Android 14.

**Comment by itamarb-ramm** [comment]
Sorry @osipxd. It seems I am having a different issue:
```
Caused by javax.crypto.AEADBadTagException:
       at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:632)
       at javax.crypto.Cipher.doFinal(Cipher.java:2132)
       at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decryptInternal(AndroidKeystoreAesGcm.java:110)
       at com.google.crypto.tink.integration.android.AndroidKeystoreAesGcm.decrypt(AndroidKeystoreAesGcm.java:93)
       at com.google.crypto.tink.KeysetHandle.decrypt(KeysetHandle.java:937)
       at com.google.crypto.tink.KeysetHandle.readWithAssociatedData(KeysetHandle.java:822)
       at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:803)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readMasterkeyDecryptAndParseKeyset(AndroidKeysetManager.java:383)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:303)
       at androidx.security.crypto.EncryptedFile$Builder.build(EncryptedFile.java:172)
       at io.github.osipxd.security.crypto.EncryptedDataStoreSingletonDelegate$getValue$1$1.invoke(EncryptedDataStoreDelegate.kt:128)
       at io.github.osipxd.security.crypto.EncryptedDataStoreSingletonDelegate$getValue$1$1.invoke(EncryptedDataStoreDelegate.kt:116)
       at io.github.osipxd.security.crypto.EncryptedDataStoreFactoryKt.createEncrypted(EncryptedDataStoreFactory.kt:78)
       at io.github.osipxd.security.crypto.EncryptedDataStoreSingletonDelegate.getValue(EncryptedDataStoreDelegate.kt:116)
       at io.github.osipxd.security.crypto.EncryptedDataStoreSingletonDelegate.getValue(EncryptedDataStoreDelegate.kt:89)
```

**Comment by osipxd** [comment]
@itamarb-ramm, could you ensure that encrypted files are excluded from backup?
[Here](https://github.com/tink-crypto/tink-java/issues/23#issuecomment-1908016875) is a discussion of the bug similar to yours.

**Comment by alvindizon** [comment]
Seems like there's going to be an update with Tink that can hopefully address this issue, see https://github.com/tink-crypto/tink-java/issues/23#issuecomment-2390792438

**Comment by osipxd** [comment]
> Seems like there's going to be an update with Tink that can hopefully address this issue

Thank you for the link! I'll keep an eye on this ticket

**Comment by osipxd** [comment]
The new API has been released with [Tink 1.16](https://github.com/tink-crypto/tink-java/releases/tag/v1.16.0) 🎉

**Comment by parveen-sharma-huru** [comment]
We’re currently using version 1.1.1-beta03 in our production environment and are experiencing a significant number of crashes. Kindly look into the issue @osipxd.
Below is a stack trace from our crash reports:

[com.huru_issue_6a4cd5ebcf34e8fd921f963c2d82f179_crash_session_691155A003DB00015F3221C7CE8C27FD_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/23450817/com.huru_issue_6a4cd5ebcf34e8fd921f963c2d82f179_crash_session_691155A003DB00015F3221C7CE8C27FD_DNE_0_v2_stacktrace.txt)

**Comment by niteshhuru** [comment]
@osipxd I am also facing lot of crashes on multiple devices in production. can you please share the solution ASAP.

**Comment by parveen-sharma-huru** [comment]
@osipxd any update on the crashes??

**Comment by osipxd** [comment]
Hi there
The update for the library is on my list, however I had no time to work on it, I'm sorry. I'll raise its priority and will try to migrate to new Tink APIs as soon as possible. I understand your frustration and will provide more details about progress as soon as I have them, to make things more transparent.

Meantime it should be possible to reduce number of crashes by manual creation of encryption keys during the app start with retry logic. Tink [has an example](https://github.com/tink-crypto/tink-java/blob/1.20/examples/android/helloworld/app/src/main/java/com/helloworld/TinkApplication.java) of keys creation. This would help to solve problems with master key generation and would make it possible to gracefully handle the case when master key exists, but not useable. In fact this code is what I'm going to include in the library (with some changes to provide better API).

Designing this API in the way it remains flexible and concise is not trivial. And this task blocks me from releasing a new version. Adopting this code for a specific app should be much easier.
