### ISSUE TITLE
Preferences DataStore crashes if obfuscation enabled

### ISSUE THREAD

**Issue by osipxd** [osipxd/encrypted-datastore#7]
### Stacktrace
```
Fatal Exception: java.lang.RuntimeException: Field value_ for e4.c not found. Known fields are [public int e4.c.e, public java.lang.Object e4.c.f, public static final e4.c e4.c.g, public static volatile g4.x$b e4.c.h]
       at androidx.datastore.preferences.protobuf.MessageSchema.reflectField(MessageSchema.java:608)
       at androidx.datastore.preferences.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:479)
       at androidx.datastore.preferences.protobuf.MessageSchema.newSchema(MessageSchema.java:221)
       at androidx.datastore.preferences.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
       at androidx.datastore.preferences.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
       at androidx.datastore.preferences.protobuf.Protobuf.schemaFor(Protobuf.java:93)
       at androidx.datastore.preferences.protobuf.Protobuf.schemaFor(Protobuf.java:107)
       at androidx.datastore.preferences.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:170)
       at androidx.datastore.preferences.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:386)
       at androidx.datastore.preferences.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:394)
       at androidx.datastore.preferences.core.PreferencesSerializer.getValueProto(PreferencesSerializer.kt:76)
       at androidx.datastore.preferences.core.PreferencesSerializer.writeTo(PreferencesSerializer.kt:63)
       at androidx.datastore.preferences.core.PreferencesSerializer.writeTo(PreferencesSerializer.kt:36)
       at io.github.osipxd.datastore.encrypted.EncryptedSerializer.writeTo(EncryptedSerializer.kt:23)
       at androidx.datastore.core.SingleProcessDataStore.writeData$datastore_core(SingleProcessDataStore.kt:426)
       at androidx.datastore.core.SingleProcessDataStore.transformAndWrite(SingleProcessDataStore.kt:410)
       at androidx.datastore.core.SingleProcessDataStore$transformAndWrite$1.invokeSuspend(SingleProcessDataStore.kt:14)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### Workarounds

1. Add dependency `androidx.datastore:datastore-preferences` to build script
2. Add proguard rules:
    ```pro
    -keepclassmembers class androidx.datastore.preferences.PreferencesProto$Value {
         private java.lang.Object value_;
         private int valueCase_;
    }

    -keepclassmembers class * extends androidx.datastore.preferences.protobuf.GeneratedMessageLite {
        <fields>;
    }
    ```

**Comment by osipxd** [comment]
Proguard rules are included in `androidx.datastore:datastore`, but not in `androidx.datastore:datastore-core` which I use as a dependency:
https://github.com/osipxd/encrypted-datastore/blob/c85439f4c0f7959060562f8ec8aa7ad876027b67/gradle/libs.versions.toml#L9-L10

Will be fixed in the next versoin.
